import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={
          inter.className +
          "bg-[#faf8f0] flex w-full h-full overflow-hidden flex-col flex-nowrap overscroll-y-none touch-none"
        }
      >
        {children}
      </body>
    </html>
  );
}
